---
- name: Verify
  hosts: all

  tasks:
    - name: Execute packer version to capture output
      command: "packer --version"
      register: packer_current_version

    - name: Ensure packer version output contains correct version string
      assert:
        that:
          - packer_current_version.rc == 0

    - name: Ensure docker compose is correct version
      assert:
        that:
          - "'1.7.10' in packer_current_version.stdout"
          