---
- name: Verify
  hosts: all
  tasks:

    - name: Execute packer version to capture output
      command: "packer --version"
      register: packer_current_version
      ignore_errors: yes

    - name: Ensure packer is not installed
      assert:
        that:
          - packer_current_version.rc != 0