---
#--------------------------------------------------------------
# Tasks
#--------------------------------------------------------------
- name: Install Packer
  include_tasks: "install.yml"
  when: >
    uninstall == false
  tags:
    - install

- name: Uninstall Packer
  include_tasks: "uninstall.yml"
  when: >
    uninstall == true
  tags:
    - uninstall